#! /usr/bin/env ruby

require 'pg'
require 'date'
require 'pry'
require 'io/console'

class ExpensesData
  def initialize(dbname)
    @connection = PG.connect(dbname: dbname)
  end

  def list_expenses
    result = connection.exec('SELECT * FROM expenses;')

    display(result)
  end

  def add_expense(amount, memo, date = Date.today)
    sql = "INSERT INTO expenses (amount, memo, created_on) VALUES ($1, $2, $3);"
    connection.exec_params(sql, [amount, memo, date])
  end

  def search_expenses(criteria)
    sql = "SELECT * FROM expenses WHERE memo ILIKE $1"
    result =  connection.exec_params(sql, ["%#{criteria}%"])
    display(result)
  end

  def delete_expense(id)
    sql = "SELECT * FROM expenses WHERE id = $1"
    result = connection.exec_params(sql, [id])

    if result.num_tuples.zero?
      puts "There is no expense with the id '#{id}'."
    else
      sql = "DELETE FROM expenses WHERE id = $1"
      connection.exec_params(sql, [id])

      puts "The following expense has been deleted:"
      display(result)
    end
  end

  def delete_all_expenses
    sql = "DELETE FROM expenses;"
    connection.exec(sql)
  end

  private
  attr_reader :connection

  def display(result)
    puts result.fields.join(' | ')

    result.each do |tuple|
      puts tuple.values.join(' | ')
    end
  end
end

class CLI
  def initialize
    @expenses = ExpensesData.new('expenses')
  end

  def run(args)
    command = args.shift
    case command
    when 'list'
      expenses.list_expenses
    when 'add'
      if (2..3).include?(args.length)
        expenses.add_expense(*args)
      else
        puts 'You must provide an amount and memo.'
      end
    when 'search'
      criteria = args.first
      if criteria
        expenses.search_expenses(criteria)
      else
         puts 'You must provide search criteria.'
       end
    when 'delete'
      id = args.first
      expenses.delete_expense(id)
    when 'clear'
      puts "This will remove all expenses. Are you sure? (y/n)"
      answer = $stdin.getch

      if answer == 'y'
        expenses.delete_all_expenses
        puts "All expenses have been deleted."
      end
    else
      display_help
    end
  end

  def display_help
    puts <<~MESSAGE
      An expense recording system

      Commands:

      add AMOUNT MEMO [DATE] - record a new expense
      clear - delete all expenses
      list - list all expenses
      delete NUMBER - remove expense with id NUMBER
      search QUERY - list expenses with a matching memo field
    MESSAGE
  end

  private
  attr_reader :expenses
end



CLI.new.run(ARGV)
